sistema-pedidos-atos2/caixas/urls.py
from django.urls import path
from . import views

app_name = 'caixa'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('reiniciar/', views.reiniciar, name='reiniciar'),
    path('pagar/<int:pk>/', views.marcar_como_pago, name='marcar_como_pago'),

]

sistema-pedidos-atos2/comandas/urls.py
from django.urls import path
from . import views

app_name = 'comandas'

urlpatterns = [
    path('', views.comanda_list, name='comanda_list'),
    path('nova/', views.comanda_create, name='comanda_create'),
    path('pix/<int:pk>/', views.comanda_pix, name='comanda_pix'),
    path('cartao/<int:pk>/', views.comanda_cartao, name='comanda_cartao'),
    path('reiniciar/', views.reiniciar_comandas, name='reiniciar_comandas'),
    path('voucher/<int:pk>/', views.gerar_voucher_view, name='gerar_voucher'),
]

sistema-pedidos-atos2/sistema_pedidos_atos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comandas/', include('comandas.urls')),
    path('caixa/', include('caixas.urls')),
]

sistema-pedidos-atos2/caixas/models.py
from django.db import models

# Create your models here.

sistema-pedidos-atos2/comandas/models.py
from django.db import models

from django.db import models

class Comanda(models.Model):
    nome = models.CharField(max_length=100)
    forma_pagamento = models.CharField(max_length=20, choices=[
        ('dinheiro', 'Dinheiro'),
        ('pix', 'Pix'),
        ('cartao', 'Cartão'),
    ])
    pedido = models.CharField(max_length=100)  # ⬅️ ADICIONE ESTA LINHA
    pago = models.BooleanField(default=False)

    def total(self):
        return sum(item.preco for item in self.itens.all())



class Item(models.Model):
    comanda = models.ForeignKey(Comanda, related_name='itens', on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=6, decimal_places=2)

sistema-pedidos-atos2/caixas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from comandas.models import Comanda

def dashboard(request):
    comandas = Comanda.objects.filter(pago=False)
    total = comandas.count()
    total_pix = comandas.filter(forma_pagamento='pix').count()
    total_cartao = comandas.filter(forma_pagamento='cartao').count()

    context = {
        'comandas': comandas,
        'total': total,
        'total_pix': total_pix,
        'total_cartao': total_cartao,
    }
    return render(request, 'caixa_dashboard.html', context)

def reiniciar(request):
    if request.method == 'POST':
        Comanda.objects.all().delete()
    return redirect('caixa:dashboard')


def finalizar_pedido(request, pk):
    comanda = get_object_or_404(Comanda, pk=pk)
    comanda.status = 'feito'
    comanda.save()
    return redirect('caixa:dashboard')


def marcar_como_pago(request, pk):
    comanda = get_object_or_404(Comanda, pk=pk)
    comanda.pago = True  # <--- usar o campo booleano existente
    comanda.save()
    return redirect('caixa:dashboard')  # Redireciona para a lista atualizada

sistema-pedidos-atos2/comandas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Comanda, Item
from django.db import connection
import os
from django.conf import settings
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from django.http import FileResponse


COMBOS = {
    'Hamburguer + Suco': [
        {'nome': 'Hamburguer', 'preco': 15.00},
        {'nome': 'Suco', 'preco': 5.00},
    ],
    'Hamburguer + Refri': [
        {'nome': 'Hamburguer', 'preco': 15.00},
        {'nome': 'Refrigerante', 'preco': 6.00},
    ],
}
def comanda_list(request):
    return render(request, 'comanda_list.html')


def comanda_create(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        pagamento = request.POST.get('pagamento')
        pedido = request.POST.get('pedido')

        comanda = Comanda.objects.create(
            nome=nome,
            forma_pagamento=pagamento,
            pedido=pedido
        )

        # Cria os itens com base no combo escolhido
        for item in COMBOS.get(pedido, []):
            Item.objects.create(
                comanda=comanda,
                nome=item['nome'],
                preco=item['preco']
            )

        if pagamento == 'pix':
            return redirect('comandas:comanda_pix', pk=comanda.pk)
        elif pagamento == 'cartao':
            return redirect('comandas:comanda_cartao', pk=comanda.pk)
        else:
            return redirect('comandas:comanda_list')

    return render(request, 'comanda_form.html')


def comanda_pix(request, pk):
    comanda = get_object_or_404(Comanda, pk=pk)
    return render(request, 'comanda_pix.html', {'comanda': comanda})

def comanda_cartao(request, pk):
    comanda = get_object_or_404(Comanda, pk=pk)
    return render(request, 'comanda_cartao.html', {'comanda': comanda})


def reiniciar_comandas(request):
    if request.method == 'POST':
        Item.objects.all().delete()
        Comanda.objects.all().delete()

        # Resetar o ID da tabela Comanda
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM sqlite_sequence WHERE name='comandas_comanda'")

        return redirect('comandas:comanda_list')

    return redirect('comandas:comanda_list')


def gerar_voucher_view(request, pk):
    comanda = get_object_or_404(Comanda, pk=pk)

    # Gera o PDF com base na comanda
    gerar_voucher_comanda(pk)

    # Caminho do arquivo gerado
    caminho_pdf = os.path.join('vouchers', f'voucher_{pk}.pdf')

    return FileResponse(open(caminho_pdf, 'rb'), content_type='application/pdf')


def gerar_voucher_comanda(comanda_id, pasta='vouchers'):
    os.makedirs(pasta, exist_ok=True)

    comanda = Comanda.objects.prefetch_related('itens').get(pk=comanda_id)
    nome_cliente = comanda.nome
    pedido_descricao = comanda.pedido
    numero_comanda = comanda.pk

    nome_arquivo = os.path.join(pasta, f'voucher_{numero_comanda}.pdf')

    largura, altura = 21 * cm, 9 * cm
    c = canvas.Canvas(nome_arquivo, pagesize=(largura, altura))

    # Logo centralizado
    logo_path = os.path.join(settings.BASE_DIR, 'static/img/logo_atos2.png')
    if os.path.exists(logo_path):
        logo = ImageReader(logo_path)
        c.drawImage(logo, (largura - 3.5 * cm) / 2, altura - 4.8 * cm, width=3.5 * cm, height=3.5 * cm, mask='auto')

    # Nome do cliente (substitui "Atos 2")
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(largura / 2, altura - 5.4 * cm, nome_cliente)

    # Descrição do pedido
    c.setFont("Helvetica", 14)
    c.drawCentredString(largura / 2, altura - 6.2 * cm, pedido_descricao)

    # Número da comanda
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(largura / 2, altura - 7.5 * cm, str(numero_comanda))

    c.showPage()
    c.save()
    print(f"Voucher salvo: {nome_arquivo}")

sistema-pedidos-atos2/caixas/templates/caixa_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Caixa{% endblock %}

{% block content %}
<div class="container mt-4">
  {% for comanda in comandas %}
    <div class="card mb-3 shadow-sm">
      <div class="card-body">
        <h5 class="card-title">Nome: {{ comanda.nome }}</h5>
        <h5 class="card-title">Comanda {{ comanda.id }}</h5>
        <h5 class="card-title">Pedido: {{ comanda.pedido }}</h5>



        <ul class="list-unstyled">
          {% for item in comanda.itens.all %}
            <li>1x {{ item.nome }}</li>
          {% endfor %}
        </ul>

        <p class="mb-2"><strong>Total:</strong> R$ {{ comanda.total|floatformat:2 }}</p>

        <div class="d-flex gap-2">
          <form method="post" action="{% url 'caixa:marcar_como_pago' comanda.id %}">
            {% csrf_token %}
              <button type="submit" class="btn btn-success btn-sm" style="width: 60px; height: 49px;">✔️</button>
          </form>
            <a href="{% url 'comandas:gerar_voucher' comanda.pk %}" target="_blank" class="btn btn-warning btn-sm">
                <img src="{% static 'img/voucher.png' %}" alt="Ícone" style="width: 40px; height: 40px;">
            </a>
        </div>
      </div>
    </div>
  {% endfor %}
                  <form action="{% url 'comandas:reiniciar_comandas' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Reiniciar Comandas</button>
            </form>
</div>
{% endblock %}

sistema-pedidos-atos2/comandas/templates/comanda_cartao.html
{% extends 'base.html' %}
{% block title %}Pagamento - Cartão{% endblock %}

{% block content %}
<div class="text-center mt-4">
    <h3>Pague quando receber</h3>
    <p>Você escolheu pagar com cartão. Um voluntário levará a maquininha até você.</p>
</div>
{% endblock %}

sistema-pedidos-atos2/comandas/templates/comanda_form.html
{% extends 'base.html' %}
{% block title %}Nova Comanda{% endblock %}

{% block content %}
<div class="mt-4">
    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_nome" class="form-label">Nome</label>
            <input type="text" name="nome" class="form-control" id="id_nome" placeholder="Digite seu nome" required>
        </div>

        <div class="mb-3">
            <label for="id_pedido" class="form-label">Pedido</label>
            <select name="pedido" id="id_pedido" class="form-select" required>
                <option value="" disabled selected>Selecione o pedido</option>
                <option value="Hamburguer + Suco">Hamburguer + Suco R$ - 20,00</option>
                <option value="Hamburguer + Refri">Hamburguer + Refri - R$ 21,00</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="id_pagamento" class="form-label">Pagamento</label>
            <select name="pagamento" id="id_pagamento" class="form-select" required>
                <option value="" disabled selected>Selecione o pagamento</option>
                <option value="pix">Pix</option>
                <option value="cartao">Cartão</option>
            </select>
        </div>

        <div class="d-grid">
            <button type="submit" class="btn btn-danger">Finalizar</button>
        </div>
    </form>
</div>
{% endblock %}

sistema-pedidos-atos2/comandas/templates/comanda_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Comandas{% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-center justify-content-center" style="height: 80vh;">
    <img src="{% static 'img/logo_atos2.png' %}" alt="Logo Atos 2" style="max-height: 200px;" class="mb-4">

    <a href="{% url 'comandas:comanda_create' %}" class="btn btn-danger rounded-circle" style="width: 100px; height: 100px; font-size: 3rem;">
        +
    </a>
</div>
{% endblock %}

sistema-pedidos-atos2/comandas/templates/comanda_pix.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Pagamento - Pix{% endblock %}

{% block content %}
<div class="text-center mt-4">
    <h3>Escaneie o QR Code abaixo para pagar</h3>
    <img src="{% static 'img/qr_code.jpeg' %}" alt="QR Code Pix" class="img-fluid my-4" style="max-width: 300px;">
    <p>Após o pagamento, aguarde a confirmação.</p>
</div>
{% endblock %}

sistema-pedidos-atos2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Atos 2{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{% static 'img/logo_atos2-icon.png' %}" type="image/png">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .footer-nav {
            position: fixed;
            bottom: 0;
            width: 100%;
            background: #fff;
            border-top: 1px solid #ddd;
            display: flex;
            justify-content: space-around;
            padding: 1rem 0;
        }
        .footer-nav a {
            flex: 1;
            text-align: center;
            text-decoration: none;
            padding: 1rem;
            color: #fff;
            background-color: #ff3b30;
            border-radius: 5px;
            margin: 0 5px;
        }
        .main-content {
            padding-bottom: 70px; /* espaço pro footer fixo */
        }
    </style>
</head>
<body>
    <div class="container main-content">
        {% block content %}
        {% endblock %}
    </div>

    <div class="footer-nav">
        <a href="{% url 'comandas:comanda_list' %}">Comandas</a>
        <a href="{% url 'caixa:dashboard' %}">Caixa</a>
    </div>
</body>
</html>